name: CI - Develop
on: 
  pull_request:
    branches:
      - develop
jobs:
  ci-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      
      - run: go test -coverprofile=coverage.out
        working-directory: ./app

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  horusec:
    runs-on: ubuntu-latest
    steps:
     - name: Running Horus Security
       id: step_horusec
       run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p ./
